version: '3.7'

services:
  api:
    container_name: nest_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - pgsql
  pgsql:
    container_name: 'pgsql'
    image: postgres:alpine
    networks:
      - backend
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      #POSTGRES_USER: pguser
      #POSTGRES_PASSWORD: pgpassword.en
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
networks:
  backend:      
volumes:
  pg-data: